// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcID_nYQKKXWtLyqGd6wsdPvzp8XFW7L4',
    appId: '1:285103521442:web:f486a7c6247873f6ce61fb',
    messagingSenderId: '285103521442',
    projectId: 'm80esports-58416',
    authDomain: 'm80esports-58416.firebaseapp.com',
    storageBucket: 'm80esports-58416.firebasestorage.app',
    measurementId: 'G-CQD8EKRY82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmFeTrtoQSmwoS1qGt7E6jgUU0Tp1nX8',
    appId: '1:285103521442:android:307b20f7a5a92ee9ce61fb',
    messagingSenderId: '285103521442',
    projectId: 'm80esports-58416',
    storageBucket: 'm80esports-58416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDhrPqqLdx5T-k1dcgduLQR_UHXMzHbl8',
    appId: '1:285103521442:ios:41a7c5fd4671e693ce61fb',
    messagingSenderId: '285103521442',
    projectId: 'm80esports-58416',
    storageBucket: 'm80esports-58416.firebasestorage.app',
    iosBundleId: 'com.example.m80esports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDhrPqqLdx5T-k1dcgduLQR_UHXMzHbl8',
    appId: '1:285103521442:ios:41a7c5fd4671e693ce61fb',
    messagingSenderId: '285103521442',
    projectId: 'm80esports-58416',
    storageBucket: 'm80esports-58416.firebasestorage.app',
    iosBundleId: 'com.example.m80esports',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcID_nYQKKXWtLyqGd6wsdPvzp8XFW7L4',
    appId: '1:285103521442:web:dba5b11ec111d7d9ce61fb',
    messagingSenderId: '285103521442',
    projectId: 'm80esports-58416',
    authDomain: 'm80esports-58416.firebaseapp.com',
    storageBucket: 'm80esports-58416.firebasestorage.app',
    measurementId: 'G-XHTVELTLN8',
  );
}
